BeerStore/Models/Supplier.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BeerStore.Models
{
    public class Supplier
    {
        public int SupplierId { get; set; }
        
        [Required]
        public string Name { get; set; }
        
        [Required]
        public string Phone { get; set; }
        
        [Required]
        public virtual Address Address { get; set; }
        
        [Required]
        public int AddressKey { get; set; }
        
        [Required]
        public List<ProductSupplier> ProductSuppliers { get; set; }
    }
}

BeerStore/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerStore.Models;
using Microsoft.EntityFrameworkCore.Internal;

namespace BeerStore.Controllers
{
    public class SupplierController : Controller
    {
        private readonly AppDbContext _context;

        public SupplierController(AppDbContext context)
        {
            _context = context;
        }
        
        public class EditModel
        {
            public int SupplierId { get; set; }
            
            [DataType(DataType.Text)]
            [Display(Name = "Supplier Name")]
            [StringLength(100, 
                ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", 
                MinimumLength = 2)]
            public string Name { get; set; }
            
            [DataType(DataType.PhoneNumber)]
            [Display(Name = "Phone")]
            public string Phone { get; set; }
            
            [DataType(DataType.Text)]
            [Display(Name = "City")]
            [StringLength(100, 
                ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", 
                MinimumLength = 2)]
            public string City { get; set; }
            
            [DataType(DataType.Text)]
            [Display(Name = "Street")]
            [StringLength(100, 
                ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", 
                MinimumLength = 2)]
            public string Street { get; set; }
            
            [DataType(DataType.Text)]
            [Display(Name = "Home number")]
            public int HomeNumber { get; set; }
            
            [DataType(DataType.PostalCode)]
            [Display(Name = "Zip code")]
            public int ZipCode { get; set; }
            
            [Display(Name = "Products")]
            public List<int> Products { get; set; }
            
        }

        // GET: Supplier
        public async Task<IActionResult> Index(string searchString, string searchIndex)
        {
            var appDbContext = _context.Suppliers.Include(s => s.Address).AsQueryable();
            
            if (! String.IsNullOrEmpty(searchString))
            {
                switch (searchIndex)
                {
                    case "phone":
                        appDbContext = appDbContext.Where(s => s.Phone.ToLower().Contains(searchString.ToLower()));
                        break;
                    case "city":
                        appDbContext = appDbContext.Where(s => s.Address.City.ToLower().Contains(searchString.ToLower()));
                        break;
                    case "product":
                        appDbContext = appDbContext.Include(s => s.ProductSuppliers)
                            .Where(s => s.ProductSuppliers.Exists(p => p.Product.Name.ToLower().Contains(searchString.ToLower())));
                        break;
                    default:
                        appDbContext = appDbContext.Where(s => s.Name.ToLower().Contains(searchString.ToLower()));
                        break;
                }
            }
            return View(await appDbContext.ToListAsync());
        }

        // GET: Supplier/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Suppliers
                .Include(s => s.Address)
                .FirstOrDefaultAsync(m => m.SupplierId == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // GET: Supplier/Create
        public IActionResult Create()
        {
            ViewData["Products"] = new MultiSelectList(_context.Products, "ProductId", "Name");
            return View();
        }

        // POST: Supplier/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ([Bind("SupplierId,Name,Phone,City,HomeNumber,Street,ZipCode," +
                                                       "Products")] EditModel newSupplier)
        {
            Supplier supplier = new Supplier()
            {
                Name = newSupplier.Name,
                Phone = newSupplier.Phone,
                SupplierId = newSupplier.SupplierId,
                Address = new Address()
                {
                    City = newSupplier.City,
                    Number = newSupplier.HomeNumber,
                    Street = newSupplier.Street,
                    ZipCode = newSupplier.ZipCode,
                }
            };
            supplier.ProductSuppliers = newSupplier.Products.Select(productId =>
                new ProductSupplier()
                {
                    SupplierId = supplier.SupplierId,
                    Supplier = supplier,
                    ProductId = productId,
                    Product = _context.Products
                        .FirstOrDefault(product => product.ProductId == productId)
                }).ToList();
            if (ModelState.IsValid)
            {
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "Name");
            return View();
        }

        // GET: Supplier/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentSupplier = await _context.Suppliers.Include(supp => supp.Address)
                .Include(supp => supp.ProductSuppliers)
                .FirstOrDefaultAsync(m => m.SupplierId == id);
            if (currentSupplier == null)
            {
                return NotFound();
            }
            ViewData["Products"] = new SelectList(_context.Products, "ProductId", "Name");
            
            EditModel newSupplier = new EditModel()
            {
                SupplierId = currentSupplier.SupplierId,
                Name = currentSupplier.Name,
                Phone = currentSupplier.Phone,
                City = currentSupplier.Address.City,
                Street = currentSupplier.Address.Street,
                HomeNumber = currentSupplier.Address.Number,
                ZipCode = currentSupplier.Address.ZipCode,
                Products = new List<int>(),
            };
            foreach (var product in currentSupplier.ProductSuppliers)
            {
                newSupplier.Products.Add(product.ProductId);
            }
            return View(newSupplier);
        }

        // POST: Supplier/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SupplierId,Name,Phone,City,HomeNumber,Street,ZipCode," +
                                                    "Products")] EditModel supplier)
        {
            if (id != supplier.SupplierId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Supplier currentSupplier = new Supplier
                {
                    Name = supplier.Name,
                    Phone = supplier.Phone,
                    SupplierId = supplier.SupplierId,
                    Address = new Address()
                    {
                        City = supplier.City,
                        Number = supplier.HomeNumber,
                        Street = supplier.Street,
                        ZipCode = supplier.ZipCode,
                    }
                };
                if (supplier.Products != null)
                {
                    currentSupplier.ProductSuppliers = supplier.Products.Select(productId =>
                        new ProductSupplier()
                        {
                            SupplierId = supplier.SupplierId,
                            ProductId = productId
                        }).ToList();
                }
                else
                {
                    currentSupplier.ProductSuppliers = new List<ProductSupplier>();
                }

                try
                {
                    _context.Suppliers.Include(s => s.ProductSuppliers)
                        .FirstOrDefault(s => s.SupplierId == supplier.SupplierId)
                        ?.ProductSuppliers.ForEach(ps => _context.Entry(ps).State = EntityState.Deleted);
                    currentSupplier.ProductSuppliers.ForEach(ps => _context.Entry(ps).State = EntityState.Added);
                    var originalSupplier = _context.Suppliers
                        .FirstOrDefault(s => s.SupplierId == currentSupplier.SupplierId);
                    _context.Entry(originalSupplier ?? throw new NullReferenceException()).State = EntityState.Detached;
                    _context.Update(currentSupplier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(supplier.SupplierId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;

BeerStore/Views/Supplier/Create.cshtml
@model BeerStore.Controllers.SupplierController.EditModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Supplier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeNumber" class="control-label"></label>
                <input asp-for="HomeNumber" class="form-control" />
                <span asp-validation-for="HomeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Products" class="control-label">Products</label>
                @foreach(var product in ViewBag.Products) {
                    <div name="checkboxs">
                        <label>
                            <input type="checkbox" name="Products" value="@product.Value"> @product.Text
                        </label>
                    </div>
                }
                <span asp-validation-for="Products" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

BeerStore/Views/Supplier/Delete.cshtml
@model BeerStore.Models.Supplier

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Supplier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.Street)
            @Html.DisplayFor(model => model.Address.Number),
            @Html.DisplayFor(model => model.Address.City),
            @Html.DisplayFor(model => model.Address.ZipCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SupplierId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

BeerStore/Views/Supplier/Details.cshtml
@model BeerStore.Models.Supplier

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol?callback=LoadMap" defer></script>
    <script type="text/javascript">
        $('#map').ready(function loadDots() {
            var name="@Model.Name";
            var address="@Model.Address.Street @Model.Address.Number, @Model.Address.City @Model.Address.ZipCode";
            loadJSON(name, address);
        });
    </script>
</head>
<body>
<div>
    <h4>Supplier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.City)
        </dd>
    </dl>
</div>
<div id="map" style="position: relative; width: 100%; height: 500px;" onload="LoadMap()"></div>

<div>
    @if (User != null && User.HasClaim("permission", "update"))
    {
        <a asp-action="Edit" asp-route-id="@Model.SupplierId">Edit</a> <span>|</span>
    }
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

BeerStore/Views/Supplier/Edit.cshtml
@model BeerStore.Controllers.SupplierController.EditModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Supplier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SupplierId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeNumber"></label>
                <input asp-for="HomeNumber" class="form-control" />
                <span asp-validation-for="HomeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Products" class="control-label">Products</label>
                @foreach(var product in ViewBag.Products) {
                    <div name="checkboxs">
                        <label>
                            <input type="checkbox" name="Products" value="@product.Value"
                                   @if(Model.Products.Contains(int.Parse(product.Value)))
                                   { <text>checked</text> }> @product.Text
                        </label>
                    </div>
                }
                <span asp-validation-for="Products" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

BeerStore/Views/Supplier/Index.cshtml
@model IEnumerable<BeerStore.Models.Supplier>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol?callback=LoadMap" defer></script>
    <script type="text/javascript">
        $('#map').ready(function loadDots() {
            @foreach (var item in Model)
            {
                @:var name = "@item.Name";
                @:var address = "@item.Address.Street @item.Address.Number, @item.Address.City @item.Address.ZipCode";
                @:loadJSON(name, address);
            }
        });
    </script>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="form-group">
    <label class="control-label">Search</label><br/>
    
    @using (Html.BeginForm("Index", "Supplier", FormMethod.Get))
    {
        <p>
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new
            {
                @style="width: 73%; display: inline",
                @class="form-control"
            })
            @Html.DropDownList("searchIndex",
            new List<SelectListItem>
            {
                new SelectListItem{ Text="Name", Value = "name" },
                new SelectListItem{ Text="Phone", Value = "phone" },
                new SelectListItem{ Text="City", Value = "city" },
                new SelectListItem{ Text="Product", Value = "product" }
            },
            new
            {
                @style="width: 15%; display: inline",
                @class="form-control",            
            })
            <input type="submit" value="Search" class="form-control" style="width: 10%; display: inline"/>
        </p>
    }
</div>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address.Street)
                @Html.DisplayFor(modelItem => item.Address.Number),
                @Html.DisplayFor(modelItem => item.Address.City),
                @Html.DisplayFor(modelItem => item.Address.ZipCode)
            </td>
            <td>
                @if (User != null && User.HasClaim("permission", "update"))
                {
                    <a asp-action="Edit" asp-route-id="@item.SupplierId">Edit</a> <span>|</span>
                }
                <a asp-action="Details" asp-route-id="@item.SupplierId">Details</a> |
                @if (User != null && User.HasClaim("permission", "delete"))
                {
                    <a asp-action="Delete" asp-route-id="@item.SupplierId">Delete</a>
                }
            </td>
        </tr>
    }
    </tbody>
</table>
<div id="map" style="position: relative; width: 100%; height: 500px;" onload="LoadMap()"></div>
</body>
</html>